import Head from 'next/head'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.container}>
        <header>
          <p>React JS</p>
        </header>

        <main className={styles.secao_titulo}>
          <section>
            <h1>React JS</h1>
            <p>Biblioteca JavaScript para criar SPAs</p>
            <a href='https://react.dev/' target="_blank">Site Oficial</a>
          </section>
        </main>
      </div>
    </>
  )
}
